version: '3'
services:
  frontend:
    build:
      context: ../song-app-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Stream
